### PR TITLE
WIP: Implement Aggregator Views

### PR DESCRIPTION
**Pull request by vroland**

### CODE REVIEW

**Comment by Lodifice** [comment]
What is the point of this materialized view? My intention was to iteratively fill tables in order to minimize load. Using materialized views this way would recreate the entire stack every hour.

**Comment by vroland** [comment]
I wanted to set up some test queries, so a materialized view was the easiest way ;) But sure, this should be replaced by a table sooner or later. Feel free to do that :)

Yes, I think I will cherry-pick the tool fixes to master.

**Comment by Lodifice** [comment]
What's with the huge changes in the dashboard?

**Comment by vroland** [comment]
that is mostly chanded indentation through migrating from `python -m json.tool` and sed to jq.

**Pull request merged**
